import logging
import math
import os
import threading
import time
from datetime import datetime, timezone

try:
    from pynput import keyboard, mouse
    HAS_PYNPUT = True
except Exception:
    keyboard = None
    mouse = None
    HAS_PYNPUT = False

import db

_lock = threading.Lock()
_state: dict = {
    "status": "idle",   # "idle" | "recording" | "stopped"
    "buffer": [],
    "last_mouse_pos": None,
}
_kb_listener = None
_mouse_listener = None

_SIDECAR_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SIDECAR_DIR)
_MACROS_DIR = os.path.join(_PROJECT_ROOT, "data", "macros")

_KEY_MAP = {
    "escape": "esc",
    "page_up": "pageup",
    "page_down": "pagedown",
    "caps_lock": "capslock",
    "num_lock": "numlock",
    "scroll_lock": "scrolllock",
    "print_screen": "printscreen",
    "backspace": "backspace",
    "enter": "enter",
    "space": "space",
    "tab": "tab",
    "up": "up",
    "down": "down",
    "left": "left",
    "right": "right",
    "home": "home",
    "end": "end",
    "insert": "insert",
    "delete": "delete",
}


def _pynput_to_pyautogui(detail: str) -> str:
    """Convert pynput key string to a pyautogui key name."""
    if detail.startswith("'") and detail.endswith("'") and len(detail) >= 3:
        return detail[1:-1]
    if detail.startswith("Key."):
        name = detail[4:]
        return _KEY_MAP.get(name, name)
    return detail


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def start_recording(workflow_id: int | None) -> dict:
    global _kb_listener, _mouse_listener

    with _lock:
        if _state["status"] == "recording":
            return {"ok": False, "error": "already recording"}
        _state["buffer"].clear()
        _state["last_mouse_pos"] = None
        _state["status"] = "recording"

    def on_press(key):
        try:
            with _lock:
                _state["buffer"].append({
                    "type": "key_press",
                    "timestamp": time.time(),
                    "detail": str(key),
                    "x": None,
                    "y": None,
                })
        except Exception:
            logging.exception("Macro recorder key error")

    def on_click(x, y, button, pressed):
        if not pressed:
            return
        try:
            with _lock:
                _state["buffer"].append({
                    "type": "mouse_click",
                    "timestamp": time.time(),
                    "detail": str(button),
                    "x": x,
                    "y": y,
                })
        except Exception:
            logging.exception("Macro recorder click error")

    def on_move(x, y):
        try:
            with _lock:
                last = _state["last_mouse_pos"]
                if last is not None:
                    dx, dy = x - last[0], y - last[1]
                    if math.sqrt(dx * dx + dy * dy) <= 20:
                        return
                _state["last_mouse_pos"] = (x, y)
                _state["buffer"].append({
                    "type": "mouse_move",
                    "timestamp": time.time(),
                    "detail": "move",
                    "x": x,
                    "y": y,
                })
        except Exception:
            logging.exception("Macro recorder move error")

    if not HAS_PYNPUT:
        return {"ok": False, "error": "pynput not available — install on Windows to record"}

    _kb_listener = keyboard.Listener(on_press=on_press)
    _kb_listener.start()
    _mouse_listener = mouse.Listener(on_click=on_click, on_move=on_move)
    _mouse_listener.start()

    return {"ok": True, "state": "recording"}


def stop_recording() -> dict:
    global _kb_listener, _mouse_listener

    with _lock:
        if _state["status"] != "recording":
            return {"ok": False, "error": "not recording"}
        _state["status"] = "stopped"
        event_count = len(_state["buffer"])

    if _kb_listener:
        _kb_listener.stop()
        _kb_listener = None
    if _mouse_listener:
        _mouse_listener.stop()
        _mouse_listener = None

    return {"ok": True, "state": "stopped", "event_count": event_count}


def get_recording_buffer() -> list[dict]:
    with _lock:
        return list(_state["buffer"])


def get_recording_status() -> dict:
    with _lock:
        return {
            "state": _state["status"],
            "event_count": len(_state["buffer"]),
        }


def generate_pyautogui_script(events: list[dict], name: str) -> str:
    header = (
        f"# Macro: {name}\n"
        f"# Generated by Personal Process Miner\n"
        f"# Events: {len(events)}\n"
        f"import pyautogui\n"
        f"import time\n\n"
        f"pyautogui.FAILSAFE = True\n"
        f"pyautogui.PAUSE = 0.05\n"
    )

    if not events:
        return header + "\n# No events recorded\n"

    lines: list[str] = []
    prev_ts = events[0]["timestamp"]

    for step, evt in enumerate(events, start=1):
        delta = min(evt["timestamp"] - prev_ts, 2.0)
        prev_ts = evt["timestamp"]

        lines.append(f"\n# Step {step}")

        if delta > 0.01:
            lines.append(f"time.sleep({delta:.3f})")

        t = evt.get("type", "")
        if t == "key_press":
            key = _pynput_to_pyautogui(evt.get("detail", ""))
            lines.append(f"pyautogui.press('{key}')")
        elif t == "mouse_click":
            x, y = evt.get("x"), evt.get("y")
            if x is not None and y is not None:
                lines.append(f"pyautogui.click({x}, {y})")
        elif t == "mouse_move":
            x, y = evt.get("x"), evt.get("y")
            if x is not None and y is not None:
                lines.append(f"pyautogui.moveTo({x}, {y}, duration=0.1)")

    return header + "\n".join(lines) + "\n"


def save_macro(name: str, workflow_id: int | None) -> dict:
    try:
        buffer = get_recording_buffer()
        script = generate_pyautogui_script(buffer, name)

        os.makedirs(_MACROS_DIR, exist_ok=True)
        name_slug = "".join(
            c if (c.isalnum() or c == "_") else "_"
            for c in name.lower().replace(" ", "_")
        )
        script_path = os.path.join(_MACROS_DIR, f"{name_slug}.py")

        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script)

        automation_id = db.insert_automation({
            "workflow_id": workflow_id,
            "name": name,
            "script_type": "pyautogui",
            "script_body": script,
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

        return {
            "ok": True,
            "automation_id": automation_id,
            "script_path": script_path,
            "event_count": len(buffer),
        }
    except Exception as exc:
        logging.exception("save_macro error")
        return {"ok": False, "error": str(exc)}
