import logging
import os
from datetime import datetime, timezone

import db

_SIDECAR_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SIDECAR_DIR)
_MACROS_DIR = os.path.join(_PROJECT_ROOT, "data", "macros")

_BROWSER_NAMES = {"chrome", "firefox", "edge", "safari", "browser"}


def _ts_to_float(evt: dict) -> float:
    """Convert an event's ISO timestamp string to a Unix epoch float for delta math."""
    ts = evt.get("timestamp") or ""
    if not ts:
        return 0.0
    try:
        dt = datetime.fromisoformat(ts)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.timestamp()
    except (ValueError, AttributeError):
        return 0.0
_BROWSER_SUFFIXES = [
    " - Google Chrome",
    " - Mozilla Firefox",
    " - Firefox",
    " - Microsoft Edge",
    " - Safari",
]


# ---------------------------------------------------------------------------
# Primitives
# ---------------------------------------------------------------------------


def is_browser_event(event: dict) -> bool:
    app = (event.get("app_name") or "").lower()
    return any(name in app for name in _BROWSER_NAMES)


def extract_url_from_title(window_title: str) -> str | None:
    if not window_title:
        return None
    # Heuristic 1: contains "- http" — extract the URL after the dash
    idx = window_title.find("- http")
    if idx != -1:
        return window_title[idx + 2:].strip() or None
    # Heuristic 2: strip known browser suffix and return remainder if it looks like a URL
    for suffix in _BROWSER_SUFFIXES:
        if window_title.endswith(suffix):
            candidate = window_title[: -len(suffix)].strip()
            if candidate.startswith(("http://", "https://")):
                return candidate
            return None
    return None


def classify_event(event: dict) -> str:
    t = event.get("event_type", "")
    detail = event.get("detail", "") or ""

    if t == "window_focus" and is_browser_event(event):
        return "navigate"
    if t == "mouse_click":
        return "click"
    if t == "key_press":
        # Unwrap pynput quoted format: "'a'" -> "a"
        if detail.startswith("'") and detail.endswith("'") and len(detail) >= 3:
            inner = detail[1:-1]
        else:
            inner = detail
        # Special keys like Key.space, Key.shift are "unknown"; printable chars are "type"
        if inner and not inner.startswith("Key."):
            return "type"
        return "unknown"
    if t == "mouse_scroll":
        return "scroll"
    return "unknown"


def _extract_char(event: dict) -> str:
    detail = event.get("detail", "") or ""
    if detail.startswith("'") and detail.endswith("'") and len(detail) >= 3:
        return detail[1:-1]
    if len(detail) == 1:
        return detail
    return ""


def group_keystrokes(events: list[dict]) -> list[dict]:
    result: list[dict] = []
    i = 0
    while i < len(events):
        evt = events[i]
        if classify_event(evt) != "type":
            result.append(evt)
            i += 1
            continue

        # Accumulate consecutive type events within 2 seconds
        chars = [_extract_char(evt)]
        base_ts = _ts_to_float(evt)
        last_ts = base_ts
        j = i + 1

        while j < len(events):
            next_evt = events[j]
            next_ts = _ts_to_float(next_evt)
            if classify_event(next_evt) == "type" and (next_ts - last_ts) <= 2.0:
                chars.append(_extract_char(next_evt))
                last_ts = next_ts
                j += 1
            else:
                break

        merged = dict(evt)
        merged["detail"] = "".join(chars)
        merged["timestamp"] = base_ts
        result.append(merged)
        i = j

    return result


# ---------------------------------------------------------------------------
# Script generation
# ---------------------------------------------------------------------------


def generate_playwright_script(events: list[dict], name: str) -> str:
    browser_events = [e for e in events if is_browser_event(e)]

    header = (
        f"# Playwright script: {name}\n"
        f"# Generated by Personal Process Miner\n"
    )

    if not browser_events:
        return (
            header
            + "# Steps: 0\n"
            + "from playwright.sync_api import sync_playwright\n"
            + "import time\n\n"
            + "# No browser events detected in this workflow\n"
        )

    grouped = group_keystrokes(browser_events)

    step_num = 0
    step_lines: list[str] = []
    prev_ts = _ts_to_float(grouped[0])

    for i, evt in enumerate(grouped):
        ts = _ts_to_float(evt)
        delta = min(ts - prev_ts, 3.0) if i > 0 else 0.0
        prev_ts = ts

        if delta > 0.01:
            step_num += 1
            step_lines.append(f"\n        # Step {step_num}: Wait")
            step_lines.append(f"        time.sleep({delta:.3f})")

        step_num += 1
        kind = classify_event(evt)

        if kind == "navigate":
            url = extract_url_from_title(evt.get("window_title") or "") or "about:blank"
            step_lines.append(f"\n        # Step {step_num}: Navigate")
            step_lines.append(f'        page.goto("{url}")')
        elif kind == "click":
            x, y = evt.get("x"), evt.get("y")
            if x is not None and y is not None:
                step_lines.append(f"\n        # Step {step_num}: Click at ({x}, {y})")
                step_lines.append(f"        page.mouse.click({x}, {y})")
        elif kind == "type":
            text = evt.get("detail", "")
            # Unwrap if still in pynput quoted format
            if text.startswith("'") and text.endswith("'") and len(text) >= 3:
                text = text[1:-1]
            text_escaped = text.replace('"', '\\"').replace("\\", "\\\\")
            step_lines.append(f"\n        # Step {step_num}: Type text")
            step_lines.append(f'        page.keyboard.type("{text_escaped}")')
        elif kind == "scroll":
            y = evt.get("y", 0) or 0
            step_lines.append(f"\n        # Step {step_num}: Scroll")
            step_lines.append(f"        page.mouse.wheel(0, {y})")
        else:
            # Unknown events are comments — don't increment step counter
            step_num -= 1
            step_lines.append(
                f"\n        # Unknown event: {evt.get('event_type', 'unknown')}"
            )

    body = "\n".join(step_lines)

    return (
        header
        + f"# Steps: {step_num}\n"
        + "from playwright.sync_api import sync_playwright\n"
        + "import time\n\n"
        + "def run():\n"
        + "    with sync_playwright() as p:\n"
        + "        browser = p.chromium.launch(headless=False)\n"
        + "        page = browser.new_page()\n"
        + body
        + "\n\n"
        + "        browser.close()\n\n"
        + 'if __name__ == "__main__":\n'
        + "    run()\n"
    )


def save_playwright_script(
    events: list[dict], name: str, workflow_id: int | None
) -> dict:
    try:
        script = generate_playwright_script(events, name)

        os.makedirs(_MACROS_DIR, exist_ok=True)
        name_slug = "".join(
            c if (c.isalnum() or c == "_") else "_"
            for c in name.lower().replace(" ", "_")
        )
        script_path = os.path.join(_MACROS_DIR, f"{name_slug}_playwright.py")

        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script)

        # Count action steps
        step_count = script.count("page.")

        from datetime import datetime, timezone
        automation_id = db.insert_automation({
            "workflow_id": workflow_id,
            "name": name,
            "script_type": "playwright",
            "script_body": script,
            "created_at": datetime.now(timezone.utc).isoformat(),
        })

        return {
            "ok": True,
            "automation_id": automation_id,
            "script_path": script_path,
            "step_count": step_count,
        }
    except Exception as exc:
        logging.exception("save_playwright_script error")
        return {"ok": False, "error": str(exc)}
